### ISSUE TITLE
Track reason for transaction

### ISSUE THREAD

**Issue by notdrone** [91paisa/91paisa-dashboard#49]
context:
>We must know what is the context of each remittance, hence we must have a way to capture it. How are we doing it? This is the next step we have to execute.

**Comment by notdrone** [comment]
Could add a textbox in transaction detail page

**Comment by kumartanmay** [comment]
We need to understand customer's moment of struggle when he decides to do money transfer. So we must try to know his purpose of remittance, what were his alternatives and why did he select our product? We have to determine the forces amplifying the use of 91paisa and continue doing it in a better way.

**Comment by samkit-jain** [comment]
@notdrone Yes. The process will be similar to saving comments for a call.

**Comment by notdrone** [comment]
This will show up in the transaction page below split list:
and might look something like this:
<img width="1037" alt="screen shot 2018-04-25 at 4 42 39 pm" src="https://user-images.githubusercontent.com/5713737/39242547-f2e7e6c8-48a7-11e8-988f-9e706f6329c9.png">

Does this work for you guys?
